packages:
  - ./

allowBuilds:
  unrs-resolver: false

minimumReleaseAge: 10080 # 7 days in minutes
minimumReleaseAgeExclude:
  - pnpm@11.20.0
  - brace-expansion@1.1.17 || 1.1.18 || 5.0.9

overrides:
  brace-expansion@<1.1.17: ^1.1.17
  brace-expansion@<1.1.18: ^1.1.18
  brace-expansion@>=4.0.0 <5.0.9: ^5.0.9
  chokidar: '>=5'
  semver: '>=7'

trustPolicy: no-downgrade
trustPolicyExclude:
  - 'vite@6.4.1'
